import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
export default function Home({ data }) {
  //console.log(data.results);
  const radius = (rate) => {
    let result = rate > 70 ? styles.heighAverage : styles.lowAverage;
    return result;
  };

  const myLoader = ({ src, width, quality }) => {
    return `https://www.themoviedb.org/t/p/w220_and_h330_face/${src}?w=${width}&q=${
      quality || 75
    }`;
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <h1 className={`${styles.title}`}>Movies</h1>
          <div className="d-flex justify-content-between row">
            {data.results.map((item) => {
              return (
                <div className=" col-sm-12  col-md-3" key={item.id}>
                  <div className="position-relative rounded shadow  d-flex justify-content-between flex-column my-4  mx-2">
                    <div
                      className={`${styles.link} d-flex justify-content-center align-items-center bg-light  rounded-circle`}
                    >
                      <Link
                        href={{
                          pathname: `/movie/[id]`,
                          query: {
                            id: item.id,
                          },
                        }}
                      >
                        <a className="d-block fw-bold fs-3">
                          <p>...</p>
                        </a>
                      </Link>
                    </div>
                    <Image
                      loader={myLoader}
                      src={item.poster_path}
                      alt="Picture of the Movie Poster"
                      width={500}
                      height={500}
                    />
                    <div
                      className={`${styles.average} ${radius(
                        item.vote_average * 10
                      )}  mx-3 rounded-circle bg-dark  d-flex justify-content-center align-items-center text-light fw-bold`}
                    >
                      <p className={`${styles.notRotate}`}>
                        {item.vote_average * 10} <sup>*</sup>
                      </p>
                    </div>
                    <h4 className="px-3 pt-3 " style={{ height: "90px" }}>
                      {item.title}
                    </h4>
                    <p className="px-3 gray">{item.release_date}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`
  https://api.themoviedb.org/3/movie/popular?api_key=931fa26364246e318b07fbc8f8a75ead`);

  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
